version: '3.8'

services:
  devopin-app:
    image: ${DOCKER_USERNAME:-username}/devopin-app:latest
    container_name: devopin-app
    ports:
      - "8080:8080"
    volumes:
      # Persistent database storage
      - ./devopin-data:/app/data
      # Mount agent socket from host
      - /run/devopin-agent.sock:/run/devopin-agent.sock
      # Optional: mount custom .env
      # - ./.env:/app/.env
    environment:
      - DATABASE_URL=sqlite:////app/data/devopin.db
      - AGENT_SOCKET_PATH=/run/devopin-agent.sock
      - FALLBACK_SOCKET_PATH=/tmp/devopin-agent.sock
    restart: unless-stopped
    depends_on:
      - devopin-agent
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Include devopin-agent service jika available sebagai container
  # devopin-agent:
  #   image: devopin/agent:latest
  #   container_name: devopin-agent
  #   volumes:
  #     - /run/devopin-agent.sock:/run/devopin-agent.sock
  #   restart: unless-stopped

volumes:
  devopin-data:
    driver: local