"""Added field user_timezone to users table

Revision ID: 4314b0122793
Revises: 9f04b3a1577f
Create Date: 2025-07-01 07:23:39.319107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4314b0122793'
down_revision: Union[str, None] = '9f04b3a1577f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_timezone')
    # ### end Alembic commands ###
