"""Added threshold_setting table

Revision ID: 9f04b3a1577f
Revises: 28186918557e
Create Date: 2025-06-29 11:34:16.284062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f04b3a1577f'
down_revision: Union[str, None] = '28186918557e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric_type', sa.Enum('CPU', 'MEMORY', 'DISK', name='thresholdtype'), nullable=False),
    sa.Column('condition', sa.Enum('GREATER_THAN', 'LESS_THAN', 'EQUALS', name='thresholdcondition'), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='thresholdseverity'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('source_filter', sa.String(length=100), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thresholds_id'), 'thresholds', ['id'], unique=False)
    op.create_index(op.f('ix_thresholds_name'), 'thresholds', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thresholds_name'), table_name='thresholds')
    op.drop_index(op.f('ix_thresholds_id'), table_name='thresholds')
    op.drop_table('thresholds')
    # ### end Alembic commands ###
